services:
  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
      args:
        build: ${build}
    environment:
      - BUILD_ENV=${build}
    # volumes:
    #   - ./scraper:/app
  frontend:
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        build: ${build}
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        build: ${build}
    environment:
      - FLASK_ENV=${build}
    ports: 
      - "5000:5000"
    volumes:
      - ./backend:/app