services:
  db:
    build: ./db
    ports:
      - '27017:27017'
    volumes:
      - ./db:/data/db
  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
      args:
        build: ${build}
        spider_name: ${SPIDER_NAME:-superstore_spider}
    environment:
      - BUILD_ENV=${build}
      - SPIDER_ENV=${SPIDER_NAME:-superstore_spider}
    volumes:
      - ./scraper:/app
  frontend:
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        build: ${build}
    environment:
      - NODE_ENV=${build}
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
  frontend-vite:
    image: frontend-vite
    build:
      context: ./frontend-vite
      dockerfile: Dockerfile
      args:
        build: ${build}
    environment:
      - NODE_ENV=${build}
    ports:
      - "8000:8000"
    volumes:
      - ./frontend-vite:/app
  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        build: ${build}
    environment:
      - FLASK_ENV=${build}
    ports: 
      - "5000:5000"
    volumes:
      - ./backend:/app