services:
  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
      args:
        build: ${build}
    volumes:
      - ./scraper:/app
  frontend:
    image: frontend:development
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        build: ${build}
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
  backend:
    image: backend:development
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        build: ${build}
    ports: 
      - "5000:5000"
    volumes:
      - ./backend:/app