name: GitHub Actions CI/CD pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        if [ -f scraper/requirements.txt ]; then pip install -r scraper/requirements.txt; fi

    - name: Build and test
      run: |
        docker build -t scraper ./scraper
        docker run --rm -e pytest=true scraper